version: '2'

services:
  app:
    extends:
      file: ./docker/compose/supply.yml
      service: dependencies
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0 # change localhost to 0.0.0.0
    ports:
      - 3000:3000 # - host's port:container's port
    command: yarn run start